### ISSUE TITLE
Instalace z prohlížeče

### ISSUE THREAD

**Issue by JanSuchanek** [mrtnzlml/zlml.cz#29]
Ahoj, pokud instaluji přez prohlížeč tak blbne webloader.

Konkrétně při instalaci vadí:

clientVendorDir: %appDir%/../vendor-client

po změně na 

clientVendorDir: %wwwDir%/../vendor-client

je vše OK.

**Comment by mrtnzlml** [comment]
To je divné, vždy mi to fungovalo, dokonce jsem to nedávno myslím instaloval. Navíc `%appDir%/../vendor-client` i `%wwwDir%/../vendor-client` by mělo jít do stejného adresáře, jen z jiného místa. Můžeš mi prosím poslat třeba chybu kterou to píše? Hledal bych problém spíš někde jinde...

**Comment by JanSuchanek** [comment]
Hlásí:

ERROR (#0): Neither '/Users/Example/Sites/zlml.cz/app/model/../vendor-client/bootstrap/dist/css/bootstrap.min.css' or '/Users/Example/Sites/zlml.cz/www/css//Users/Example/Sites/zlml.cz/app/model/../vendor-client/bootstrap/dist/css/bootstrap.min.css' was found

Spouštím z adresy: http://localhost/zlml.cz/www

**Comment by mrtnzlml** [comment]
Něco se muselo lehce změnit ve WebLoaderu (podezírám https://github.com/janmarek/WebLoader/commit/a5575b7cf332db1e18ca8dc861af524241d746a6), ale abych pravdu řekl, tak se mi nechtělo hledat co. Mělo by to ale fungovat...
