### ISSUE TITLE
Problém s @dataProviderom

### ISSUE THREAD

**Issue by camohub** [mrtnzlml/zlml.cz#32]
Zdravím,
mám menší problém s @dataProviderom. Testujem formulár s jedným políčkom, ktoré je required. Urobil som test, kde by raz mal required prejsť a raz nie. Keď to testujem tak dostanem vždy rovnaký výsledok. Vždy ten, čo je prvý v @dataProvidery. 

``` php
public function commentFormParameters()
{
    return [
	    [ [ 'test' => 1, 'content' => '', 'do' => 'commentForm-submit' ] ],
	    [ [ 'test' => 2, 'content' => 'Some required content.', 'do' => 'commentForm-submit' ] ],
    ];
}
```
Teda prvý test by nemal prejsť a druhý áno. Ale getErrors() vracia vždy, výsledok prvého testu a nereaguje na zmenu $post prametrov.
Celý test vyzerá takto:
``` php
/**
 * @dataProvider commentFormParameters
 * @param $post
 */
public function testCommentForm( $post )
{
    $response = $this->check( 'Articles:show', [ 'title' => 'ako-islo-vajce-na-vandrovku' ], $post );
    $errors = $this->getPresenter()->getComponent( 'commentForm' )->getErrors();

    Assert::true( count( $errors ) > 0 );
    Debugger::log( $errors );
}
```
Ako to vyriešim?
Podľa všetkého s to týka podmienky v metóde check()
```php
if (!$this->__testbench_presenter) .... 
```
Takže vlastne by malo stačiť priradiť NULL?
```php
$this->__testbench_presenter = NULL;
```

**Comment by mrtnzlml** [comment]
Nepatří to spíše k [tomuto repozitáři](https://github.com/mrtnzlml/testbench)? (https://github.com/mrtnzlml/testbench) :smile:

**Comment by camohub** [comment]
Sorry, presunuté.
